/**
 * FlutterwaveClient — scoped to ServiceApplication (conventions.md §
 * Third-party integrations / Flutterwave). ServiceApplication is the only
 * wave-0 resource with a real payment leg (the CAC ₦25,000 registration
 * fee); DirectMessage/CreatorSubscription/CreditPurchase/Purchase come in
 * later waves and will build their own client behind this same
 * client-charge + server-verify pattern (or a future shared refactor) — not
 * this agent's call to make.
 *
 * Real Flutterwave test-mode credentials are not available in this sandbox
 * (declared/flutterwave-payments.json § sandboxNote) — the interface below
 * has a real implementation (RealFlutterwaveAdapter) that calls the actual
 * Flutterwave v3 REST API, and a MockFlutterwaveAdapter used by contract
 * tests / local dev (env-gated — see service-application.module.ts) so this
 * resource's own logic is fully exercised even though live Flutterwave
 * connectivity is not.
 */

export const FLUTTERWAVE_CLIENT = Symbol('FLUTTERWAVE_CLIENT');

export interface FlutterwaveChargeInit {
  txRef: string;
  amount: number;
  currency: string;
  publicKey: string;
}

export interface FlutterwaveVerifiedTransaction {
  status: 'successful' | 'failed' | string;
  amount: number;
  currency: string;
  txRef: string;
}

export interface FlutterwaveClient {
  /**
   * Builds the config the client's inline Flutterwave JS SDK charges
   * against. No outbound network call is required here (matches
   * Flutterwave's real inline-checkout pattern) — `txRef` is generated by
   * the caller (ServiceApplicationService), server-side, and always embeds
   * the pending ServiceApplication row's id so `.../verify` can correlate
   * the payment back to it without a separate transactions table (the
   * schema is frozen and defines none).
   */
  initCharge(params: { txRef: string; amount: number; currency: string }): Promise<FlutterwaveChargeInit>;

  /**
   * GET /v3/transactions/:id/verify against Flutterwave. Caller
   * cross-checks status/amount/currency/txRef before marking anything paid
   * — never trusts a client-echoed success (conventions.md).
   */
  verifyCharge(params: { transactionId: string; txRef: string }): Promise<FlutterwaveVerifiedTransaction>;
}
