"""
WALLET-18: every Unicode character whose numeric value is a single digit
(0 to 9) and that is not a decimal digit (`\\p{Nd}`): the "other number"
(No) and "letter number" (Nl) characters, such as circled, negative
circled, double circled, dingbat, Ethiopic and Roman numerals. Read from
the Unicode Character Database's numeric values (Python's `unicodedata`),
written to `src/money/receipts/unicode-digits.generated.ts`, which the
receipt's masking folds through (receipt-document.ts `foldDigits`).
Decimal digits are folded by their value in the code itself, so this table
holds only the others. Run it again when Python's Unicode version moves.

    python3 scripts/receipt/build-digit-table.py
"""

from __future__ import annotations

import unicodedata
from pathlib import Path

OUT = (
    Path(__file__).resolve().parents[2]
    / "src" / "money" / "receipts" / "unicode-digits.generated.ts"
)


def main() -> None:
    pairs = []
    for cp in range(0x110000):
        ch = chr(cp)
        if unicodedata.category(ch) not in ("No", "Nl"):
            continue
        value = unicodedata.numeric(ch, None)
        if value is None or value != int(value) or not 0 <= value <= 9:
            continue
        pairs.append((cp, int(value)))
    lines = [
        "/**",
        " * Generated by scripts/receipt/build-digit-table.py from the Unicode",
        f" * Character Database {unicodedata.unidata_version} (never edit by hand): every",
        " * character of category No or Nl whose numeric value is a whole number",
        " * from 0 to 9, as [code point, value].",
        " */",
        f"export const UNICODE_DIGIT_VERSION = '{unicodedata.unidata_version}';",
        "",
        "export const OTHER_DIGITS: ReadonlyArray<readonly [number, number]> = [",
    ]
    for i in range(0, len(pairs), 6):
        lines.append("  " + " ".join(f"[{cp}, {v}]," for cp, v in pairs[i:i + 6]))
    lines.append("];")
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {len(pairs)} characters to {OUT}")


if __name__ == "__main__":
    main()
