"""
WALLET-18: the receipt's table of number characters that are not decimal
digits (`\\p{Nd}`): the "other number" (No) and "letter number" (Nl)
characters, such as circled, negative circled, double circled, dingbat,
Ethiopic, Roman, Kaktovik numerals and the Yangqin signs.

Written to `src/money/receipts/unicode-digits.generated.ts`, which the
receipt's masking reads (receipt-document.ts `digitMasking`):
- OTHER_DIGITS: every No or Nl character whose numeric value is a whole
  number from 0 to 9, as [code point, value]. These fold to that digit.
- OTHER_NUMBERS: every other No or Nl character (fractions, numbers of 10 or
  more), as [first, last] code point ranges. These are known not to be a
  single digit and are left as they are.
A number character the runtime knows but neither list holds (one added in a
later Unicode than this table) is treated as a hidden digit (fail closed).
Decimal digits are folded by their value in the code itself, from the
runtime's own Unicode, so this table holds only the others.

Source: the Unicode Character Database's UnicodeData.txt, pinned to one
version and checked against its SHA-256 below (round 5: Python's own
`unicodedata` lagged the runtime, 14.0 against Node 22's 17.0). The
version must be at least the runtime's `process.versions.unicode`; a test
fails when it is older. To move it, change UCD_VERSION, UCD_URL and
UCD_SHA256 together and run again.

    python3 scripts/receipt/build-digit-table.py              # downloads UCD_URL
    python3 scripts/receipt/build-digit-table.py --ucd FILE   # a local copy
"""

from __future__ import annotations

import argparse
import hashlib
import urllib.request
from pathlib import Path

UCD_VERSION = "17.0.0"
UCD_URL = "https://www.unicode.org/Public/17.0.0/ucd/UnicodeData.txt"
UCD_SHA256 = "2e1efc1dcb59c575eedf5ccae60f95229f706ee6d031835247d843c11d96470c"

OUT = (
    Path(__file__).resolve().parents[2]
    / "src" / "money" / "receipts" / "unicode-digits.generated.ts"
)


def read_ucd(path: str | None) -> bytes:
    if path:
        data = Path(path).read_bytes()
    else:
        with urllib.request.urlopen(UCD_URL, timeout=60) as res:
            data = res.read()
    got = hashlib.sha256(data).hexdigest()
    if got != UCD_SHA256:
        raise SystemExit(
            f"UnicodeData.txt SHA-256 is {got}, expected {UCD_SHA256} "
            f"(Unicode {UCD_VERSION}). Not written."
        )
    return data


def numeric(field: str) -> float | None:
    """UnicodeData.txt field 8, the numeric value: '7', '-1/2', '1/16' or empty."""
    if field == "":
        return None
    if "/" in field:
        num, den = field.split("/")
        return int(num) / int(den)
    return float(field)


def ranges(cps: list[int]) -> list[tuple[int, int]]:
    out: list[tuple[int, int]] = []
    for cp in cps:
        if out and out[-1][1] == cp - 1:
            out[-1] = (out[-1][0], cp)
        else:
            out.append((cp, cp))
    return out


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--ucd", help="a local UnicodeData.txt (checked against UCD_SHA256)")
    args = parser.parse_args()

    digits: list[tuple[int, int]] = []
    others: list[int] = []
    for line in read_ucd(args.ucd).decode("utf-8").splitlines():
        fields = line.split(";")
        # No or Nl characters are never given as a <..., First>/<..., Last> range.
        if len(fields) < 15 or fields[2] not in ("No", "Nl"):
            continue
        cp = int(fields[0], 16)
        value = numeric(fields[8])
        if value is not None and value == int(value) and 0 <= value <= 9:
            digits.append((cp, int(value)))
        else:
            others.append(cp)

    lines = [
        "/**",
        " * Generated by scripts/receipt/build-digit-table.py from the Unicode",
        f" * Character Database {UCD_VERSION} (never edit by hand):",
        f" * {UCD_URL}",
        f" * SHA-256 {UCD_SHA256}",
        " * OTHER_DIGITS: every character of category No or Nl whose numeric value",
        " * is a whole number from 0 to 9, as [code point, value]. OTHER_NUMBERS:",
        " * every other No or Nl character, as [first, last] code point ranges.",
        " */",
        f"export const UNICODE_DIGIT_VERSION = '{UCD_VERSION}';",
        "",
        "export const OTHER_DIGITS: ReadonlyArray<readonly [number, number]> = [",
        *(f"  [{cp}, {v}]," for cp, v in digits),
        "];",
        "",
        "export const OTHER_NUMBERS: ReadonlyArray<readonly [number, number]> = [",
        *(f"  [{a}, {b}]," for a, b in ranges(others)),
        "];",
    ]
    OUT.write_text("\n".join(lines) + "\n")
    print(
        f"wrote {len(digits)} digits and {len(others)} other numbers "
        f"({len(ranges(others))} ranges), Unicode {UCD_VERSION}, to {OUT}"
    )


if __name__ == "__main__":
    main()
