import { readFileSync } from 'node:fs';
import { join } from 'node:path';

/**
 * TIER-01, verifier finding D1 and lead ruling N2: what `contract/openapi.json`
 * (generated by `npm run contract:build`) says about GET /plans and
 * GET /me/tier, which is what the app's types are generated from.
 *
 * - The three fields that answer null must be written the OpenAPI 3.0 way
 *   that keeps the null (`{ allOf: [{ $ref }], nullable: true }`): a
 *   `nullable` beside a bare `$ref` is ignored, and the app would be told
 *   they are never null.
 * - Every number in the two answers is a whole number (`integer`).
 */

type Schema = {
  $ref?: string;
  allOf?: Schema[];
  nullable?: boolean;
  type?: string;
  items?: Schema;
  properties?: Record<string, Schema>;
};
type Contract = {
  paths: Record<string, Record<string, unknown>>;
  components: { schemas: Record<string, Schema> };
};

const contract = JSON.parse(
  readFileSync(join(__dirname, '../../../contract/openapi.json'), 'utf8'),
) as Contract;
const schemas = contract.components.schemas;

const PLAN_SCHEMAS = [
  'PlansView',
  'PlanTierView',
  'PlanEventPassView',
  'PlanBadgeView',
  'PlanExtraProductsView',
  'PlanPackView',
  'PlanCheckoutBumpView',
  'PlanActionView',
  'PlanCapsView',
  'MyTierView',
  'MyTierSummaryView',
];

/** True when the schema lets a value be null and still names the shape. */
function nullableRef(s: Schema | undefined, name: string): boolean {
  return (
    s?.nullable === true &&
    s.$ref === undefined &&
    s.allOf?.length === 1 &&
    s.allOf[0].$ref === `#/components/schemas/${name}`
  );
}

describe('the plans contract (TIER-01)', () => {
  it('serves both routes', () => {
    expect(contract.paths['/api/hub/plans']?.get).toBeDefined();
    expect(contract.paths['/api/hub/me/tier']?.get).toBeDefined();
    for (const name of PLAN_SCHEMAS) expect(schemas[name]).toBeDefined();
  });

  it.each([
    ['MyTierView', 'tier', 'MyTierSummaryView'],
    ['MyTierView', 'eventPass', 'PlanEventPassView'],
    ['MyTierSummaryView', 'badge', 'PlanBadgeView'],
  ])('%s.%s may be null in the contract', (owner, field, named) => {
    expect(nullableRef(schemas[owner].properties?.[field], named)).toBe(true);
  });

  it('every number in the two answers is an integer', () => {
    const numbers: string[] = [];
    const walk = (s: Schema | undefined, at: string) => {
      if (!s) return;
      if (s.type === 'number') numbers.push(at);
      walk(s.items, `${at}[]`);
      for (const [k, v] of Object.entries(s.properties ?? {}))
        walk(v, `${at}.${k}`);
    };
    let integers = 0;
    for (const name of PLAN_SCHEMAS) {
      walk(schemas[name], name);
      integers += Object.values(schemas[name].properties ?? {}).filter(
        (p) => p.type === 'integer',
      ).length;
    }
    expect(numbers).toEqual([]);
    expect(schemas.PlanTierView.properties?.priceMinor?.type).toBe('integer');
    expect(integers).toBeGreaterThan(15);
  });
});
