// Run against wawu_hub_test — always via `npm run test:contract`.
process.env.DATABASE_URL =
  process.env.DATABASE_URL ??
  'postgresql://postgres:postgres@localhost:5432/wawu_hub_test?schema=public';

import { ChildProcess, spawn } from 'child_process';
import * as path from 'path';
import { INestApplication, ValidationPipe } from '@nestjs/common';
import { Test } from '@nestjs/testing';
import request from 'supertest';
import { ConfigModule } from '@nestjs/config';
import { AllExceptionsFilter } from '../../common/filters/all-exceptions.filter';
import { ResponseInterceptor } from '../../common/interceptors/response.interceptor';
import { PrismaModule } from '../../common/prisma/prisma.module';
import { PrismaService } from '../../common/prisma/prisma.service';
import { LegalIntakeModule } from '../legal-intake.module';

const USER_PLAIN = '00000000-0000-4000-8000-000000000001';
const USER_CREATOR_PRO = '00000000-0000-4000-8000-000000000003';

const MOCK_WAWU_ID_PORT = process.env.WAWU_ID_JWKS_URL
  ? new URL(process.env.WAWU_ID_JWKS_URL).port
  : '4001';
const MOCK_WAWU_ID_BASE = `http://localhost:${MOCK_WAWU_ID_PORT}`;

/**
 * Set only when a real Gemini key is configured. The brief is generated by a
 * live call — there is no stand-in — so the tests that need one say clearly
 * that they were skipped rather than passing without having run.
 */
const HAS_GEMINI = Boolean(process.env.GEMINI_API_KEY);
const itNeedsGemini = HAS_GEMINI ? it : it.skip;

async function waitForHealth(url: string, timeoutMs = 15000): Promise<boolean> {
  const start = Date.now();
  while (Date.now() - start < timeoutMs) {
    try {
      if ((await fetch(url)).ok) return true;
    } catch {
      /* not up yet */
    }
    await new Promise((r) => setTimeout(r, 200));
  }
  return false;
}

async function login(identifier: string): Promise<string> {
  const res = await fetch(`${MOCK_WAWU_ID_BASE}/auth/login`, {
    method: 'POST',
    headers: { 'content-type': 'application/json' },
    body: JSON.stringify({ identifier }),
  });
  if (!res.ok) throw new Error(`login failed for ${identifier}: ${res.status}`);
  return ((await res.json()) as { accessToken: string }).accessToken;
}

/**
 * Legal profiling.
 *
 * The behaviour worth protecting here is that the intake ADAPTS and that it
 * refuses to hand a consultant something it did not actually produce.
 *
 * Envelope note: ResponseInterceptor puts a plain result in `data`.
 */
describe('Legal intake (contract)', () => {
  let app: INestApplication;
  let prisma: PrismaService;
  let mockWawuId: ChildProcess | undefined;
  let owned = false;
  let token: string;
  let otherToken: string;
  const created: string[] = [];

  beforeAll(async () => {
    if (!(await waitForHealth(`${MOCK_WAWU_ID_BASE}/health`, 1500))) {
      mockWawuId = spawn('node', ['server.js'], {
        cwd: path.join(__dirname, '../../../mock-wawu-id'),
        env: { ...process.env, MOCK_WAWU_ID_PORT },
        stdio: 'ignore',
      });
      owned = true;
      await waitForHealth(`${MOCK_WAWU_ID_BASE}/health`);
    }

    const moduleRef = await Test.createTestingModule({
      imports: [
        ConfigModule.forRoot({ isGlobal: true }),
        PrismaModule,
        LegalIntakeModule,
      ],
    }).compile();

    app = moduleRef.createNestApplication();
    app.useGlobalPipes(
      new ValidationPipe({
        whitelist: true,
        forbidNonWhitelisted: true,
        transform: true,
      }),
    );
    app.useGlobalFilters(new AllExceptionsFilter());
    app.useGlobalInterceptors(new ResponseInterceptor());
    await app.init();

    prisma = moduleRef.get(PrismaService);
    token = await login('user@test.wawu.dev');
    otherToken = await login('creator-pro@test.wawu.dev');
  }, 40000);

  afterEach(async () => {
    await prisma.legalIntake.deleteMany({
      where: { wawuUserId: { in: [USER_PLAIN, USER_CREATOR_PRO] } },
    });
    created.length = 0;
  });

  afterAll(async () => {
    await prisma.legalIntake.deleteMany({
      where: { wawuUserId: { in: [USER_PLAIN, USER_CREATOR_PRO] } },
    });
    await app?.close();
    if (owned && mockWawuId) mockWawuId.kill();
  }, 30000);

  const start = async (matter: string, as = token) => {
    const res = await request(app.getHttpServer())
      .post('/legal/intake')
      .set('Authorization', `Bearer ${as}`)
      .send({ matter })
      .expect(201);
    created.push(res.body.data.id);
    return res.body.data;
  };

  const answer = (id: string, answers: Record<string, unknown>, as = token) =>
    request(app.getHttpServer())
      .patch(`/legal/intake/${id}/answers`)
      .set('Authorization', `Bearer ${as}`)
      .send({ answers });

  // ---- the flow ----------------------------------------------------------

  it('offers the fourteen matters, and needs a token to do it', async () => {
    await request(app.getHttpServer()).get('/legal/intake/matters').expect(401);

    const res = await request(app.getHttpServer())
      .get('/legal/intake/matters')
      .set('Authorization', `Bearer ${token}`)
      .expect(200);
    expect(res.body.data).toHaveLength(14);
    expect(res.body.data.map((m: { value: string }) => m.value)).toContain(
      'debt_recovery',
    );
  });

  it('rejects a matter that is not on the list', async () => {
    await request(app.getHttpServer())
      .post('/legal/intake')
      .set('Authorization', `Bearer ${token}`)
      .send({ matter: 'divorce_by_combat' })
      .expect(400);
  });

  it('resumes an unfinished intake instead of starting a second one', async () => {
    // People abandon forms and come back. Losing eight answers to a closed
    // tab is how an intake gets a reputation for being long.
    const first = await start('trademark');
    const second = await start('trademark');
    expect(second.id).toBe(first.id);

    const rows = await prisma.legalIntake.findMany({
      where: { wawuUserId: USER_PLAIN, matter: 'trademark' },
    });
    expect(rows).toHaveLength(1);
  });

  // ---- adaptive ----------------------------------------------------------

  it('asks trademark questions of a trademark client', async () => {
    const intake = await start('trademark');
    const ids = intake.questions.map((q: { id: string }) => q.id);
    expect(ids).toEqual(
      expect.arrayContaining(['tm_in_use', 'tm_registered_before', 'tm_scope']),
    );
  });

  it('does NOT ask them of a debt-recovery client', async () => {
    // The stated goal: somebody chasing an unpaid invoice should not see
    // fifteen entertainment questions.
    const intake = await start('debt_recovery');
    const ids = intake.questions.map((q: { id: string }) => q.id);
    expect(ids).not.toContain('tm_in_use');
    expect(ids).not.toContain('creator_rights_concern');
    expect(ids).toEqual(
      expect.arrayContaining(['debt_written_agreement', 'debt_age']),
    );
  });

  it('reveals the deadline date only once a deadline is claimed', async () => {
    const intake = await start('contract');
    const before = intake.questions.map((q: { id: string }) => q.id);
    expect(before).not.toContain('deadline_date');

    const res = await answer(intake.id, { has_deadline: 'yes' }).expect(200);
    const after = res.body.data.questions.map((q: { id: string }) => q.id);
    expect(after).toContain('deadline_date');
  });

  it('refuses an answer to a question this intake never asked', async () => {
    // `answers` is Json. Without this check the column would accept any shape
    // and the brief would render keys nobody was ever shown.
    const intake = await start('debt_recovery');
    const res = await answer(intake.id, { tm_scope: 'global' }).expect(400);
    expect(JSON.stringify(res.body)).toContain('tm_scope');
  });

  it('merges answers rather than replacing them', async () => {
    const intake = await start('contract');
    await answer(intake.id, { client_type: 'business_owner' }).expect(200);
    const res = await answer(intake.id, { based_in: 'nigeria' }).expect(200);
    expect(res.body.data.answers.client_type).toBe('business_owner');
    expect(res.body.data.answers.based_in).toBe('nigeria');
  });

  // ---- ownership ---------------------------------------------------------

  it("will not let anyone read someone else's intake", async () => {
    const intake = await start('debt_recovery');
    await request(app.getHttpServer())
      .get(`/legal/intake/${intake.id}`)
      .set('Authorization', `Bearer ${otherToken}`)
      .expect(403);
  });

  it("will not let anyone answer someone else's intake", async () => {
    const intake = await start('debt_recovery');
    await answer(intake.id, { based_in: 'ghana' }, otherToken).expect(403);
  });

  // ---- completion --------------------------------------------------------

  it('refuses to complete while required answers are missing', async () => {
    const intake = await start('trademark');
    const res = await request(app.getHttpServer())
      .post(`/legal/intake/${intake.id}/complete`)
      .set('Authorization', `Bearer ${token}`)
      .expect(400);
    expect(JSON.stringify(res.body)).toContain('tm_in_use');
  });

  it('tracks what is still outstanding as answers arrive', async () => {
    const intake = await start('debt_recovery');
    expect(intake.outstandingRequired).toContain('debt_age');
    const res = await answer(intake.id, { debt_age: '1_3y' }).expect(200);
    expect(res.body.data.outstandingRequired).not.toContain('debt_age');
  });

  /** Every required answer for a debt-recovery intake. */
  const fullDebtAnswers = {
    client_type: 'business_owner',
    based_in: 'nigeria',
    jurisdiction: 'nigeria',
    description:
      'A customer took delivery of goods in March and has not paid the invoice. They stopped replying in June.',
    stage: 'dispute',
    urgency: 'urgent',
    outcome: ['recover_money'],
    engagement: 'advice_first',
    has_documents: 'yes',
    other_party: 'yes',
    involves_money: 'yes',
    amount_band: '1m_5m',
    debt_written_agreement: 'yes',
    debt_age: '3_12m',
  };

  itNeedsGemini(
    'generates a brief on completion, and keeps the client answers beside it',
    async () => {
      const intake = await start('debt_recovery');
      await answer(intake.id, fullDebtAnswers).expect(200);

      const res = await request(app.getHttpServer())
        .post(`/legal/intake/${intake.id}/complete`)
        .set('Authorization', `Bearer ${token}`)
        .expect(201);

      const brief = res.body.data.brief;
      expect(res.body.data.status).toBe('completed');
      // The generated half.
      expect(typeof brief.analysis.summary).toBe('string');
      expect(brief.analysis.summary.length).toBeGreaterThan(0);
      expect(Array.isArray(brief.analysis.keyIssues)).toBe(true);
      // The half that is simply what the client said, which is what lets a
      // consultant tell evidence from analysis.
      const questions = brief.facts.map(
        (f: { question: string }) => f.question,
      );
      expect(questions).toContain('How long has it been owed?');
      // And it records what wrote the analysis.
      expect(brief.generatedBy).toContain('gemini');
    },
    45000,
  );

  itNeedsGemini(
    'cannot be completed twice',
    async () => {
      const intake = await start('debt_recovery');
      await answer(intake.id, fullDebtAnswers).expect(200);
      await request(app.getHttpServer())
        .post(`/legal/intake/${intake.id}/complete`)
        .set('Authorization', `Bearer ${token}`)
        .expect(201);
      await request(app.getHttpServer())
        .post(`/legal/intake/${intake.id}/complete`)
        .set('Authorization', `Bearer ${token}`)
        .expect(409);
    },
    45000,
  );

  it('reports whether the Gemini-backed cases actually ran', () => {
    // A skipped test is invisible in a summary line. This one is not: if the
    // key is missing, the assertion below records it in the output rather
    // than letting a green run imply the brief path was exercised.
    if (!HAS_GEMINI) {
      console.warn(
        'GEMINI_API_KEY is not set — brief-generation cases were SKIPPED, not passed.',
      );
    }
    expect(true).toBe(true);
  });
});
